url: https://everhood.top
host: everhood.top
domain: everhood.top
timezone: Asia/Shanghai
encoding: utf-8
permalink: '/:title'
exclude: ["README.md"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
paginate: 5

title: 回园
tagline: 观书唱令勤学道，久立疾行乐赏新。
author:
  name: '12425'
  email: 'y12425@outlook.com'
